apiVersion: v1
kind: Pod
metadata:
  name: sample-netcore-app
  labels:
    app: sample-netcore-app
spec:
  shareProcessNamespace: true
  containers:
  - name: sample-netcore-app
    image: joeelliott/sample-netcore-app:v1.1.2-2.2.5-alpine
    imagePullPolicy: IfNotPresent
    env:
    - name: COMPlus_DbgEnableMiniDump
      value: "1"
    - name: COMPlus_DbgMiniDumpName
      value: "/tmp/coredump.%d"
    - name: ASPNETCORE_URLS
      value: http://*:8080
    - name: COMPlus_DbgMiniDumpType
      value: "4"
    volumeMounts:
    - mountPath: /tmp
      name: tmp
  - name: profile-sidecar
    image: joeelliott/netcore-debugging-tools:v0.0.14-2.2.5-alpine
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    args:
    - sleep
    - "1d"
    volumeMounts:
    - mountPath: /tmp
      name: tmp
  volumes:
  - name: tmp
    emptyDir: {}
